sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        JHnNZfl+FTgF4zWLnS3Yjz3yTI19XsMuhZtfW5JEZG0iqLYTnzrYR250rkkMhZMZP717zC0r8CodaW6csrDzq75Xr11z4ujC/5KEzNYwf6bHov648YPY9AnQhMRxRYypVYwPrw5WKRPbtVUaB2pY+eQPzrz1o3XieBdo+aVYUNN/NVKQHTgm1CyhEyKbSq6IS33kz7I6M+jhXTujkyzMk5btOA4h587sXG7s59BjISinv4e27IouwPiIgRN/vkfR8kWBNoRVSOWh7ikkNMhPd7LFo3b5t0bS7iggDshjoHAhqvHG6afGoxih6H9acPJt1zmmR5ZgEngC5kqNEvHyCvuM4AfVkgmyEOaMi/OW0ieoAhw5rbE8FprurUdGuBipH2efFhDbp2TaBmTcHXehbxj0guZ1jGg7SG3mnJFO69BdoMDhDmmnN3lJfnhjdvCtmk8JiYI/h1tAiqs1T2doBFnPQ8EY3rtbavnYu9AlWxM+16VgDc6Yhclj6pWgOKhlWVRhcFVpW7ADUGyLZAj2Z3re2i4PvNTI4t1IFzRGSfg1DXffusDbTd7GFcS1Kg9GATgITcJCZsgIoddlWPbmCtgJhcyDNTuMjQtNoQ2vExGnrCuC9cg4SMsyYKFC6c7iORDQuxe3cfFVU8kjuW4/kc+r61JGn0DeQq8++QhRkcM=
    - secure: >-
        JZsmdkl1+3uc3+jtJeSDv/59vylSMSm1wVnigjjXY9mKyXh7jJA0oZA/nWzoTBjhTXRYjWXkBVOPhoc0mSJogGRldI9vWafNqr9paR/VIImZ5RfdfKt25rc78iRMN71mnax50UPYwM84oIlRcBa8IUBuH7QYk2+B+soaXDHh78fyxjoEhEP3QU2/c1pRpoLjOPgoSHBM+ZSM2ADwATe3CuWEi4sHR/iNnnL0QOwUGfvUQWGNEG7+DWQoGaun2H/OV2ThbGLOvo7FdD+gCZSNosaV6xcu4l3Ng7vM7wkeQEJNXy55m5xzKOV+rVA1Ckj9s7tn/VUwm768tANIeHneMg1jv92MnsLAZe0UiilGDjtyW+wu0hwTEDium+vZWMEfPXinljk+1BBtvpRde/9ZCqgB8fXDyi9gxbF7O1ANZT6BlwHIf3WsF/B384GxDRYUEZhYFT/aKghYLhSUb7UOT/gLWPVR29Ogf7mq4G98l6ORK72gw63M8fW3GbptzYL8z59vK+URgtX+XmUkfV0tGhq5fQP3DX0Q1DViZRE5sr/U5vNy/Wandq4zMuFIi4TJPn00bIJF7qK4pG2rfXdiK5lJYoOlfhDF8kmDop/I271WjOI42AVyrbrlE97En+e1vb3+QzC4RopvQaPksjd1m7vuA5+LzCHyspsDBETzL4A=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
